# This file was generated by GoReleaser. DO NOT EDIT.
class Hkmgr < Formula
  desc "Hkmgr is a virtual machine manager for the hyperkit macOS hypervisor."
  homepage "https://github.com/bensallen/hkmgr"
  version "0.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bensallen/hkmgr/releases/download/0.0.7/hkmgr_0.0.7_Darwin_x86_64.tar.gz"
    sha256 "12ad33cf4ceb455d2808eecd2181ea1e447f91fefa4a7ab05c42092912c73daf"
  elsif OS.linux?
  end
  
  depends_on "hyperkit"

  def install
    bin.install "hkmgr"
  end
end
